# Generated by Django 3.2.8 on 2021-11-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_profilemodel_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCreation',
            fields=[
                ('uname', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('upw', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ulname', models.CharField(max_length=70)),
                ('ulpassword', models.CharField(max_length=80)),
            ],
        ),
    ]
