# Generated by Django 3.2.8 on 2021-11-30 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_usercreation_userlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usercreation')),
            ],
        ),
    ]
