# Generated by Django 3.2.8 on 2021-11-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_groupname'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupname',
            name='groupname',
            field=models.CharField(default='', max_length=200),
        ),
    ]
